version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        dependency-type: 'development'
    labels:
      - dependencies
      - dependabot
      - web-team
    ignore:
      - dependency-name: 'eslint'
        versions: ['9']
      - dependency-name: 'react'
        versions: ['19']
      - dependency-name: 'react-dom'
        versions: ['19']
      - dependency-name: 'express'
        versions: ['5']
